---
- name: Create IOS Router Configuration File
  hosts: localhost
  gather_facts: False
  connection: local
  
  vars:
    csvfile: "{{ lookup('file', 'router_variables.csv') }}"
 
  tasks: 
  - include: csv-to-yml.yml 

  - include_vars: config_variables.yml

  - name: generate leaf config
    template: 
      src=config_template.j2
      dest={{ item.switch.hostname }}.cfg
    delegate_to: localhost
    with_items: "{{ devices }}"

  - name: Remove Inventory YML File (inv.yml) on playbook completion
    file:
     path: config_variables.yml
     state: absent
