---
- name: Create IOS Router Configuration File
  hosts: localhost
  gather_facts: False
  connection: local
  
  vars:
    csvfile: "{{ lookup('file', 'router_variables.csv') }}"
 
  tasks: 
  - name: Parse CSV To YAML
    template:
      src: "./csv_to_yml.j2"
      dest: "./config_variables.yml"
    run_once: true

  - include_vars: config_variables.yml

  - name: generate router configuration file
    template: 
      src=router_configuration.j2
      dest={{ item.router.hostname }}.cfg
    delegate_to: localhost
    with_items: "{{ devices }}"

  - name: Remove Inventory YML File (inv.yml) on playbook completion
    file:
     path: config_variables.yml
     state: absent
